version: '3'
services:
  node:
    container_name: apinode
    restart: always
    build: .
    env_file:
      - .env
    environment:
      - NODE_PORT=8888
      - TZ=America/Bogota
    ports:
      - "${NODE_PORT}:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongodb
    image: mongo
    env_file:
      - .env  
    environment:
      - MONGO_PORT=27017
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=tickets
    restart: on-failure  
    ports:
      - "27020:${MONGO_PORT}"
    volumes:
    - mongo-data:/data/db
volumes:
  mongo-data:    